import{STORAGE_KEY,DEFAULT_ROUTINE,advanceVirtualTime,applyElapsedTime,beginLife,feedPet,getDaysTogether,getMealStatus,getTimePhase,getVirtualNow,isSleepTime,parseState,recordPetting,recordPlay,resetVirtualTime,serializeState,setForcedHunger,setForcedSleep,updateRoutine}from'./state.js'
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)]
const e={app:$('#app'),intro:$('#intro'),home:$('#home'),introCat:$('#introCat'),touchGuide:$('#touchGuide'),namePanel:$('#namePanel'),petNameInput:$('#petNameInput'),startLife:$('#startLife'),homeHeader:$('#homeHeader'),petNameTitle:$('#petNameTitle'),dayLabel:$('#dayLabel'),memoryButton:$('#memoryButton'),catZone:$('#catZone'),windowZone:$('#windowZone'),bedZone:$('#bedZone'),bowlZone:$('#bowlZone'),toyZone:$('#toyZone'),touchBloom:$('#touchBloom'),microMessage:$('#microMessage'),firstHint:$('#firstHint'),backdrop:$('#backdrop'),foodSheet:$('#foodSheet'),memorySheet:$('#memorySheet'),memoryList:$('#memoryList'),creatorSheet:$('#creatorSheet'),debugTime:$('#debugTime'),debugState:$('#debugState'),settingsBreakfast:$('#settingsBreakfast'),settingsDinner:$('#settingsDinner'),settingsWake:$('#settingsWake'),settingsBedtime:$('#settingsBedtime'),saveRoutine:$('#saveRoutine')}
let saveHealthy=true,openSheet=null,msgTimer=null,longPressTimer=null,drag=null,state=load()
function load(){try{return parseState(localStorage.getItem(STORAGE_KEY))}catch{saveHealthy=false;return parseState(null)}}
const vNow=()=>getVirtualNow(state)
function save(){try{localStorage.setItem(STORAGE_KEY,serializeState(state));saveHealthy=true}catch{saveHealthy=false}}
async function loadRasterScene(){try{const urls=Array.from({length:8},(_,i)=>`./assets_source/scene_day_${i}.b64`),parts=await Promise.all(urls.map(u=>fetch(u,{cache:'force-cache'}).then(r=>{if(!r.ok)throw new Error(r.status);return r.text()}))),data=`url("data:image/webp;base64,${parts.join('')}")`;document.documentElement.style.setProperty('--scene-image',data);document.body.dataset.art='ready'}catch(err){document.body.dataset.art='fallback';console.error('raster scene failed',err)}}
function arrivalGrace(now=vNow()){return state.onboarded&&now-Number(state.createdAt||now)<180000}
function current(){const now=vNow(),phase=getTimePhase(now),sleep=!arrivalGrace(now)&&isSleepTime(state.routine,now,state.debug?.forceSleep),meal=getMealStatus(state,now);return{now,phase,sleep,meal}}
function render(){if(!state.onboarded)return;state=applyElapsedTime(state,vNow());save();const s=current();e.app.dataset.phase=s.phase;e.app.dataset.sleep=s.sleep?'yes':'no';e.petNameTitle.textContent=state.petName;e.dayLabel.textContent=`一緒に ${getDaysTogether(state,s.now)}日目`;e.debugTime.textContent=new Date(s.now).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'});e.debugState.textContent=saveHealthy?'保存 正常':'保存不可';e.settingsBreakfast.value=state.routine.breakfast;e.settingsDinner.value=state.routine.dinner;e.settingsWake.value=state.routine.wake;e.settingsBedtime.value=state.routine.bedtime}
function showHome(){e.intro.classList.add('hidden');e.home.classList.remove('hidden');render()}
function micro(text,duration=1800){clearTimeout(msgTimer);e.microMessage.textContent=text;e.microMessage.hidden=false;msgTimer=setTimeout(()=>e.microMessage.hidden=true,duration)}
function bloom(x,y){e.touchBloom.hidden=false;e.touchBloom.style.left=`${x}px`;e.touchBloom.style.top=`${y}px`;e.touchBloom.getAnimations().forEach(a=>a.cancel());e.touchBloom.style.animation='none';void e.touchBloom.offsetWidth;e.touchBloom.style.animation='bloom .55s ease-out forwards';setTimeout(()=>e.touchBloom.hidden=true,580)}
function haptic(ms=8){try{navigator.vibrate?.(ms)}catch{}}
function dismissHint(){e.firstHint.classList.add('dismissed')}
function open(sheet){close();openSheet=sheet;e.backdrop.hidden=false;sheet.hidden=false}
function close(){if(openSheet)openSheet.hidden=true;openSheet=null;e.backdrop.hidden=true}
function zoneFromEvent(el,ev){const r=el.getBoundingClientRect(),x=(ev.clientX-r.left)/r.width,y=(ev.clientY-r.top)/r.height;if(y<.34)return'head';if(x>.72)return'tail';if(x<.48)return'back';return'flank'}
function bindPetZone(el,{intro=false}={}){el.addEventListener('pointerdown',ev=>{el.setPointerCapture?.(ev.pointerId);drag={id:ev.pointerId,lx:ev.clientX,ly:ev.clientY,start:performance.now(),distance:0};if(!intro){dismissHint();bloom(ev.clientX,ev.clientY);haptic(6)}});el.addEventListener('pointermove',ev=>{if(!drag||drag.id!==ev.pointerId)return;const d=Math.hypot(ev.clientX-drag.lx,ev.clientY-drag.ly);drag.distance+=d;drag.lx=ev.clientX;drag.ly=ev.clientY;if(d>7){bloom(ev.clientX,ev.clientY);haptic(3)}});el.addEventListener('pointerup',ev=>{if(!drag||drag.id!==ev.pointerId)return;const pace=drag.distance/Math.max(1,performance.now()-drag.start)>1.05?'fast':'slow',z=zoneFromEvent(el,ev);drag=null;if(intro){e.touchGuide.classList.add('done');haptic(12);setTimeout(()=>{e.namePanel.hidden=false;e.petNameInput.focus({preventScroll:true})},420);return}state=recordPetting(state,z,pace,vNow());save();micro(pace==='fast'?`${state.petName}が少し顔を上げました。`:z==='head'?`${state.petName}が目を細めました。`:z==='tail'?`${state.petName}がしっぽを引き寄せました。`:`${state.petName}がそのまま近くにいます。`);render()});el.addEventListener('pointercancel',()=>drag=null)}
function renderMemories(){const items=(state.memories||[]).slice(0,12);e.memoryList.innerHTML=items.length?items.map(m=>`<article class="memory-item"><strong>${m.title}</strong><p>${m.body}</p></article>`).join(''):'<article class="memory-item"><p>まだ記録はありません。</p></article>'}
function bind(){bindPetZone(e.introCat,{intro:true});bindPetZone(e.catZone);e.startLife.addEventListener('click',()=>{const name=e.petNameInput.value.trim()||'こむぎ';state=beginLife(state,{petName:name,routine:DEFAULT_ROUTINE},Date.now());save();e.namePanel.hidden=true;showHome();micro(`${name}との暮らしが始まりました。`,2200)});e.bowlZone.addEventListener('click',()=>{dismissHint();open(e.foodSheet)});e.windowZone.addEventListener('click',()=>{dismissHint();micro(`${state.petName}と窓の外を眺めました。`)});e.bedZone.addEventListener('click',()=>{dismissHint();micro(current().sleep?`${state.petName}は眠そうです。`:`寝床を整えました。`)});e.toyZone.addEventListener('click',()=>{dismissHint();state=recordPlay(state,vNow());save();micro(`${state.petName}がおもちゃに気づきました。`);render()});$$('[data-food]').forEach(b=>b.addEventListener('click',()=>{state=feedPet(state,b.dataset.food,vNow());save();close();micro(b.dataset.food==='treat'?'おやつを少しだけ置きました。':'ごはんを置きました。');render()}));e.memoryButton.addEventListener('click',()=>{renderMemories();open(e.memorySheet)});e.backdrop.addEventListener('click',close);$$('[data-close]').forEach(b=>b.addEventListener('click',close));e.homeHeader.addEventListener('pointerdown',()=>{clearTimeout(longPressTimer);longPressTimer=setTimeout(()=>open(e.creatorSheet),1100)});['pointerup','pointercancel','pointerleave'].forEach(type=>e.homeHeader.addEventListener(type,()=>clearTimeout(longPressTimer)));$$('[data-time]').forEach(b=>b.addEventListener('click',()=>{state=advanceVirtualTime(state,Number(b.dataset.time));state=applyElapsedTime(state,vNow());save();render();micro('検証用の時刻を進めました。')}));$$('[data-debug]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.debug;if(a==='hungry')state=setForcedHunger(state,!state.debug.forceHungry);if(a==='sleep')state=setForcedSleep(state,!state.debug.forceSleep);if(a==='reset-time')state=resetVirtualTime(state);if(a==='reset'){if(confirm('確認データを削除して最初からやり直しますか？')){localStorage.removeItem(STORAGE_KEY);location.reload();return}}save();close();render()}));e.saveRoutine.addEventListener('click',()=>{state=updateRoutine(state,{breakfast:e.settingsBreakfast.value,dinner:e.settingsDinner.value,wake:e.settingsWake.value,bedtime:e.settingsBedtime.value});save();render();micro('生活時間を変更しました。')});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.onboarded){state=applyElapsedTime(state,vNow());save();render()}});window.addEventListener('pagehide',()=>{if(state.onboarded){state.lastSeenAt=vNow();save()}})}
async function init(){await loadRasterScene();bind();if(state.onboarded)showHome();setInterval(()=>state.onboarded&&render(),30000);window.__TAIL_ROOM_READY__=true;window.__TAIL_ROOM_VERSION__='0.6.0'}
init()
