export const APP_VERSION=5
export const STORAGE_KEY='tail-room-state-v5'
export const HOUR=3_600_000
export const DAY=24*HOUR
const MINUTE=60_000
const clamp=(value,min=0,max=100)=>Math.min(max,Math.max(min,Number(value)||0))
export const DEFAULT_ROUTINE=Object.freeze({breakfast:'07:30',dinner:'19:00',wake:'07:00',bedtime:'23:30'})
const validTime=(value,fallback)=>/^([01]\d|2[0-3]):[0-5]\d$/.test(String(value||''))?String(value):fallback
export const sanitizeRoutine=(routine={})=>({breakfast:validTime(routine.breakfast,DEFAULT_ROUTINE.breakfast),dinner:validTime(routine.dinner,DEFAULT_ROUTINE.dinner),wake:validTime(routine.wake,DEFAULT_ROUTINE.wake),bedtime:validTime(routine.bedtime,DEFAULT_ROUTINE.bedtime)})
export const createInitialState=(now=Date.now())=>({version:APP_VERSION,onboarded:false,kind:'cat',petName:'こむぎ',createdAt:now,lastSeenAt:now,lastFedAt:now,lastPlayedAt:null,lastPettedAt:null,fullness:82,energy:78,comfort:68,bond:8,routine:{...DEFAULT_ROUTINE},preferences:{touchCounts:{head:0,back:0,flank:0,tail:0},foodCounts:{daily:0,special:0,treat:0},favoriteTouch:null,favoriteFood:null},memories:[],sessionCount:0,debug:{timeOffsetMs:0,forceHungry:false,forceSleep:false}})
export const getVirtualNow=(state,actualNow=Date.now())=>actualNow+Number(state?.debug?.timeOffsetMs||0)
export const beginLife=(state,{petName,routine}={},now=Date.now())=>({...createInitialState(now),...state,version:APP_VERSION,onboarded:true,kind:'cat',petName:String(petName||'').trim().slice(0,10)||'こむぎ',createdAt:now,lastSeenAt:now,lastFedAt:now,fullness:82,energy:78,comfort:70,bond:10,routine:sanitizeRoutine(routine),memories:[{id:`arrival-${now}`,type:'arrival',title:'この部屋へ来た日',body:'まだ部屋の匂いを確かめている。急がず、同じ時間を重ねていこう。',createdAt:now}],sessionCount:1,debug:{timeOffsetMs:Number(state?.debug?.timeOffsetMs||0),forceHungry:false,forceSleep:false}})
export const getTimePhase=(now=Date.now())=>{const h=new Date(now).getHours();return h>=5&&h<10?'morning':h>=10&&h<17?'day':h>=17&&h<21?'evening':'night'}
const minutesOfDay=time=>{const[h,m]=validTime(time,'00:00').split(':').map(Number);return h*60+m}
export const isSleepTime=(routine,now=Date.now(),forced=false)=>{if(forced)return true;const s=sanitizeRoutine(routine),d=new Date(now),current=d.getHours()*60+d.getMinutes(),bed=minutesOfDay(s.bedtime),wake=minutesOfDay(s.wake);if(bed===wake)return false;return bed>wake?current>=bed||current<wake:current>=bed&&current<wake}
const atLocalMinutes=(date,minutes,offset=0)=>{const next=new Date(date);next.setHours(0,0,0,0);next.setDate(next.getDate()+offset);next.setMinutes(minutes);return next.getTime()}
export const getMealStatus=(state,now=Date.now())=>{const s=sanitizeRoutine(state?.routine),d=new Date(now),b=minutesOfDay(s.breakfast),n=minutesOfDay(s.dinner),meals=[{id:'yesterday-dinner',label:'夜ごはん',at:atLocalMinutes(d,n,-1)},{id:'today-breakfast',label:'朝ごはん',at:atLocalMinutes(d,b,0)},{id:'today-dinner',label:'夜ごはん',at:atLocalMinutes(d,n,0)},{id:'tomorrow-breakfast',label:'朝ごはん',at:atLocalMinutes(d,b,1)}].sort((a,c)=>a.at-c.at),latest=meals.filter(m=>m.at<=now).at(-1)||meals[0],next=meals.find(m=>m.at>now)||meals.at(-1),lateMinutes=Math.max(0,Math.floor((now-latest.at)/MINUTE)),overdue=Boolean(state?.debug?.forceHungry||(lateMinutes>=30&&Number(state?.lastFedAt||0)<latest.at));return{overdue,dueMeal:overdue?latest:null,next,lateMinutes,nextInMinutes:Math.max(0,Math.ceil((next.at-now)/MINUTE))}}
export const getDaysTogether=(state,now=Date.now())=>Math.max(1,Math.floor((now-Number(state?.createdAt||now))/DAY)+1)
export const getGrowthStage=(state,now=Date.now())=>{const day=getDaysTogether(state,now);return day<31?{id:'baby',label:'子猫期',day,scale:.86}:day<76?{id:'growing',label:'育ちざかり',day,scale:.92}:day<121?{id:'young',label:'若い時期',day,scale:.97}:{id:'adult',label:'成猫',day,scale:1}}
export const applyElapsedTime=(state,now=Date.now())=>{if(!state?.onboarded)return{...state,lastSeenAt:now};const last=Number(state.lastSeenAt||now),elapsed=Math.max(0,(now-last)/HOUR);if(elapsed<.015)return{...state,lastSeenAt:now};const sleeping=isSleepTime(state.routine,now,state.debug?.forceSleep),meal=getMealStatus(state,now);let fullness=clamp(state.fullness-elapsed*2.35,18,100),energy=sleeping?clamp(state.energy+elapsed*3.5,24,100):clamp(state.energy-elapsed*.55,24,100),comfort=clamp(state.comfort-elapsed*.28,42,100);if(meal.overdue)fullness=Math.min(fullness,meal.lateMinutes>150?30:45);let next={...state,fullness,energy,comfort,lastSeenAt:now,sessionCount:Number(state.sessionCount||0)+1};if(elapsed<4)return next;const key=new Date(now).toISOString().slice(0,10);if(next.memories.some(i=>i.id===`return-${key}`))return next;const body=sleeping?`${state.petName}は寝床で休み、物音がすると一度だけ耳を動かした。`:`${state.petName}は窓辺と寝床を行き来しながら、自分の時間を過ごしていた。`;return addMemory(next,'留守番のあと',body,now,'return',`return-${key}`)}
const favorite=counts=>Object.entries(counts||{}).sort((a,b)=>b[1]-a[1])[0]?.[0]||null
export const recordPetting=(state,zone,pace='slow',now=Date.now())=>{const z=['head','back','flank','tail'].includes(zone)?zone:'back',counts={...state.preferences.touchCounts,[z]:Number(state.preferences.touchCounts?.[z]||0)+1},welcome=z!=='tail'&&pace!=='fast';return{...state,bond:clamp(state.bond+(welcome?1.4:.2)),comfort:clamp(state.comfort+(welcome?3:pace==='fast'?-1:0)),lastPettedAt:now,preferences:{...state.preferences,touchCounts:counts,favoriteTouch:favorite(counts)}}}
export const feedPet=(state,food,now=Date.now())=>{const type=['daily','special','treat'].includes(food)?food:'daily',effect={daily:{fullness:58,comfort:2,bond:.8},special:{fullness:52,comfort:5,bond:1.2},treat:{fullness:14,comfort:4,bond:.6}}[type],counts={...state.preferences.foodCounts,[type]:Number(state.preferences.foodCounts?.[type]||0)+1};let next={...state,fullness:clamp(state.fullness+effect.fullness),comfort:clamp(state.comfort+effect.comfort),bond:clamp(state.bond+effect.bond),lastFedAt:now,debug:{...state.debug,forceHungry:false},preferences:{...state.preferences,foodCounts:counts,favoriteFood:favorite(counts)}};const text=type==='special'?`${state.petName}は香りを確かめたあと、いつもより早く食器へ顔を近づけた。`:type==='treat'?`${state.petName}は食べ終えたあと、もう一度だけ食器を見た。`:`${state.petName}は少しずつ食べ、最後に口元を舐めてから離れた。`;return addMemory(next,type==='treat'?'ひとくちのおやつ':'食事の時間',text,now,'meal')}
export const recordPlay=(state,now=Date.now())=>addMemory({...state,energy:clamp(state.energy-9),fullness:clamp(state.fullness-2),comfort:clamp(state.comfort+4),bond:clamp(state.bond+1.4),lastPlayedAt:now},'夢中になった時間',`${state.petName}はおもちゃを追い、最後に前足で押さえて動きを止めた。`,now,'play')
export function addMemory(state,title,body,createdAt=Date.now(),type='life',id=null){const item={id:id||`${type}-${createdAt}-${Math.random().toString(36).slice(2,7)}`,type,title,body,createdAt};return{...state,memories:[item,...(state.memories||[])].slice(0,60)}}
export const updateRoutine=(state,routine)=>({...state,routine:sanitizeRoutine(routine)})
export const advanceVirtualTime=(state,ms)=>({...state,debug:{...state.debug,timeOffsetMs:Number(state.debug?.timeOffsetMs||0)+Number(ms||0)}})
export const resetVirtualTime=state=>({...state,debug:{...state.debug,timeOffsetMs:0,forceHungry:false,forceSleep:false}})
export const setForcedHunger=(state,value=true)=>({...state,debug:{...state.debug,forceHungry:Boolean(value)}})
export const setForcedSleep=(state,value=true)=>({...state,debug:{...state.debug,forceSleep:Boolean(value)}})
export const serializeState=state=>JSON.stringify(state)
export const parseState=(raw,now=Date.now())=>{const initial=createInitialState(now);if(!raw)return initial;try{const parsed=JSON.parse(raw);if(parsed.version!==APP_VERSION)return initial;return{...initial,...parsed,routine:sanitizeRoutine(parsed.routine),memories:Array.isArray(parsed.memories)?parsed.memories:[],preferences:{...initial.preferences,...(parsed.preferences||{}),touchCounts:{...initial.preferences.touchCounts,...(parsed.preferences?.touchCounts||{})},foodCounts:{...initial.preferences.foodCounts,...(parsed.preferences?.foodCounts||{})}},debug:{...initial.debug,...(parsed.debug||{})}}}catch{return initial}}
